require("me.launch")
require("me.core.options")
require("me.core.keymaps")

spec("me.plugins.extras")
spec("me.plugins.mini")
-- TODO: this si great

spec("me.plugins.barbecue")
spec("me.plugins.which-key")
spec("me.plugins.colorscheme")
spec("me.plugins.lualine")
spec("me.plugins.bufferline")
spec("me.plugins.nvim-tree")
spec("me.plugins.alpha")
spec("me.plugins.notify")
spec("me.plugins.noice")
spec("me.plugins.dressing")
spec("me.plugins.trouble")
spec("me.plugins.cheatsheet")
spec("me.plugins.telescope")
spec("me.plugins.zen-mode")
spec("me.plugins.twilight")
spec("me.plugins.modes")
spec("me.plugins.editing")
spec("me.plugins.debug")
spec("me.plugins.git")
spec("me.plugins.todo")
spec("me.plugins.flash-leap")
spec("me.plugins.formatting")
spec("me.plugins.projects")
spec("me.plugins.auto-session")

spec("me.lsp.mason-lspconfig")
spec("me.lsp.lsp-signature")
spec("me.lsp.cmp")
spec("me.lsp.lsp-ui")
spec("me.lsp.treesitter")

require("me.lazy")
